name: Backend CD

on:
 push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
      
      - name: Detect Changes on files
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            app:
              - "app/**"
